# Atividade Prática — Aula 3: Limpeza, Preparação e Qualidade dos Dados com Pandas

Esta atividade foi construída com base nos slides da Aula 3, que destacam a **limpeza como a fundação invisível** de qualquer dashboard confiável. O objetivo aqui não é apenas "fazer funcionar", mas tomar decisões conscientes sobre tipos, valores ausentes, duplicidades, variáveis derivadas e exportação da base limpa. fileciteturn2file0

## Regras desta atividade
- Você deve **construir os códigos**.
- O notebook orienta os passos, mas não entrega as soluções prontas.
- Sempre que fizer uma decisão de limpeza, **documente o porquê** em comentário ou célula markdown.
- Ao final, exporte uma base limpa para uso nas próximas aulas.

## Dataset desta atividade
Arquivo bruto: `vendas_brasil_aula3_bruto.csv`

## 1. Preparação do ambiente

Importe as bibliotecas necessárias para trabalhar com:
- leitura de dados
- tratamento de nulos
- identificação de infinitos
- exportação do resultado final

**Sugestão:** Pandas e NumPy já resolvem toda a atividade.

In [2]:
# Atividade Prática — Aula 3: Limpeza, Preparação e Qualidade dos Dados com Pandas

# ## 1. Preparação do ambiente

import pandas as pd
import numpy as np

# Configurações para exibição
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

print("✅ Bibliotecas importadas com sucesso!")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

✅ Bibliotecas importadas com sucesso!
Pandas version: 2.2.2
NumPy version: 2.0.2

## 2. Leitura da base bruta

Leia o arquivo `vendas_brasil_aula3_bruto.csv` em um DataFrame chamado `df`.

Depois:
1. Exiba as primeiras linhas
2. Exiba as últimas linhas
3. Observe visualmente se já existem sinais de sujeira

In [3]:
# ## 2. Leitura da base bruta

# Leitura do arquivo CSV
df = pd.read_csv('vendas_brasil_aula3_bruto.csv')

# 1. Exibir primeiras linhas
print("=== Primeiras 10 linhas do dataset bruto ===")
display(df.head(10))

# 2. Exibir últimas linhas
print("\n=== Últimas 10 linhas do dataset bruto ===")
display(df.tail(10))

# 3. Observações iniciais sobre sujeira
print("\n=== Observações preliminares ===")
print("- Verificar possíveis valores ausentes nas primeiras linhas")
print("- Verificar se há valores como 'NaN', 'null' ou strings vazias")
print("- Verificar se as datas estão em formato consistente")
print("- Verificar se há valores negativos em colunas que deveriam ser positivas")

=== Primeiras 10 linhas do dataset bruto ===

,pedido_id,data,uf,canal,categoria,produto,cliente_id,quantidade,receita,lucro,observacao
0,1000,2024/04/29,SP,Loja Física,Informática,Notebook Pro,C134,1,4535.11,1289.83,ok
1,1001,2024-06-17,PR,NaN,Informática,Notebook Pro,C106,1,4005.59,541.36,entrega rápida
2,1002,2024-05-27,PR,Marketplace,Periféricos,Teclado Mecânico,C131,1,309.02,128.26,entrega rápida
3,1003,2024-07-08,SP,Marketplace,Informática,Notebook Pro,C148,2,7943.78,1574.09,ok
4,1004,2024-05-20,RS,Online,Informática,Notebook Pro,C105,5,19926.65,4281.84,ok
5,1005,2024-02-26,RJ,Loja Física,Periféricos,Teclado Mecânico,C155,2,752.94,375.76,NaN
6,1006,2024-07-29,RJ,Loja Física,Áudio,Headset Pro,C143,4,1154.6,491.00,NaN
7,1007,2024-09-23,PR,Online,Informática,Monitor 27,C150,5,6938.5,1379.84,NaN
8,1008,2024-08-19,SC,Loja Física,Áudio,Caixa de Som,C165,1,389.08,138.19,ok
9,1009,2024-11-18,NaN,Loja Física,Periféricos,Teclado Mecânico,C133,1,316.41,153.73,entrega rápida

=== Últimas 10 linhas do dataset bruto ===

,pedido_id,data,uf,canal,categoria,produto,cliente_id,quantidade,receita,lucro,observacao
218,1218,2024-08-05,RJ,Online,Telefonia,Tablet Plus,C107,4,8294.92,2183.46,ok
219,1219,2024-07-29,SC,Online,Periféricos,Mouse Gamer,C166,3,445.53,174.90,ok
220,1132,2024-01-29,PR,Marketplace,Telefonia,Smartphone X,C123,3,8870.79,2326.37,ok
221,1148,2024-03-18,mg,Loja Física,Informática,Notebook Pro,C179,5,21240.2,6245.67,entrega rápida
222,1093,2024-05-13,BA,Marketplace,Informática,Monitor 27,C170,2,2699.72,724.07,cliente premium
223,1180,2024-03-11,SC,Loja Física,Telefonia,Smartphone X,C158,1,2563.44,415.42,NaN
224,1015,2024-02-26,RS,Online,Informática,Notebook Pro,C102,3,15011.49,NaN,cliente premium
225,1115,2024-07-29,MG,Loja Física,Informática,Notebook Pro,C144,3,12566.04,2879.76,NaN
226,1172,2024-11-11,ES,Loja Física,Informática,Notebook Pro,C128,3,13154.04,3408.22,entrega rápida
227,1209,2024-05-27,MG,Marketplace,Áudio,Caixa de Som,C121,2,810.2,282.52,NaN

=== Observações preliminares ===
- Verificar possíveis valores ausentes nas primeiras linhas
- Verificar se há valores como 'NaN', 'null' ou strings vazias
- Verificar se as datas estão em formato consistente
- Verificar se há valores negativos em colunas que deveriam ser positivas

## 3. Check-up inicial do dataset

Com base no checklist de um dataset "clean" apresentado na aula, faça um diagnóstico inicial da base. fileciteturn2file0

### Sua missão
Use comandos que permitam responder:
- Qual é o tamanho da base?
- Quais são os tipos atuais das colunas?
- Existem valores nulos?
- Há colunas com tipo inadequado?
- Há algo que pareça impedir análises confiáveis?

In [4]:
# ## 3. Check-up inicial do dataset

print("=== CHECK-UP INICIAL DO DATASET ===\n")

# 1. Tamanho da base
print(f"1. Dimensões da base: {df.shape[0]} linhas e {df.shape[1]} colunas")

# 2. Tipos atuais das colunas
print("\n2. Tipos de dados atuais:")
print(df.dtypes)

# 3. Valores nulos
print("\n3. Valores nulos por coluna:")
print(df.isnull().sum())

# 4. Percentual de nulos
print("\n4. Percentual de nulos por coluna:")
print((df.isnull().sum() / len(df) * 100).sort_values(ascending=False))

# 5. Informações gerais
print("\n5. Informações gerais (info()):")
df.info()

# 6. Estatísticas descritivas das colunas numéricas
print("\n6. Estatísticas descritivas:")
display(df.describe())

# 7. Análise de valores únicos em colunas categóricas
print("\n7. Valores únicos em colunas categóricas:")
categoricas = df.select_dtypes(include=['object']).columns
for col in categoricas:
    print(f"\n{col}: {df[col].nunique()} valores únicos")
    print(f"Exemplos: {df[col].unique()[:10]}")

=== CHECK-UP INICIAL DO DATASET ===

1. Dimensões da base: 228 linhas e 11 colunas

2. Tipos de dados atuais:
pedido_id       int64
data           object
uf             object
canal          object
categoria      object
produto        object
cliente_id     object
quantidade      int64
receita        object
lucro         float64
observacao     object
dtype: object

3. Valores nulos por coluna:
pedido_id      0
data           0
uf             5
canal          5
categoria      5
produto        0
cliente_id     0
quantidade     0
receita        2
lucro          6
observacao    50
dtype: int64

4. Percentual de nulos por coluna:
observacao   21.93
lucro         2.63
uf            2.19
canal         2.19
categoria     2.19
receita       0.88
pedido_id     0.00
data          0.00
produto       0.00
cliente_id    0.00
quantidade    0.00
dtype: float64

5. Informações gerais (info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pedido_id   228 non-null    int64
 1   data        228 non-null    object
 2   uf          223 non-null    object
 3   canal       223 non-null    object
 4   categoria   223 non-null    object
 5   produto     228 non-null    object
 6   cliente_id  228 non-null    object
 7   quantidade  228 non-null    int64
 8   receita     226 non-null    object
 9   lucro       222 non-null    float64
 10  observacao  178 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 19.7+ KB

6. Estatísticas descritivas:

       pedido_id  quantidade   lucro
count     228.00      228.00  222.00
mean     1110.32        2.99 1333.26
std        63.56        1.19 1352.84
min      1000.00        1.00  106.78
25%      1055.75        2.00  385.00
50%      1111.50        3.00  750.70
75%      1165.25        4.00 1925.12
max      1219.00        6.00 6335.03

7. Valores únicos em colunas categóricas:

data: 62 valores únicos
Exemplos: ['2024/04/29' '2024-06-17' '2024-05-27' '2024-07-08' '2024-05-20'
 '2024-02-26' '2024-07-29' '2024-09-23' '2024-08-19' '2024-11-18']

uf: 11 valores únicos
Exemplos: ['SP' 'PR' 'RS' 'RJ' 'SC' nan 'ES' 'BA' 'rj' 'MG']

canal: 6 valores únicos
Exemplos: ['Loja Física' nan 'Marketplace' 'Online' 'ONLINE' 'MarketPlace'
 'Loja fisica']

categoria: 6 valores únicos
Exemplos: ['Informática' 'Periféricos' 'Áudio' 'Telefonia' nan 'Perifericos'
 'telefonia ']

produto: 8 valores únicos
Exemplos: ['Notebook Pro' 'Teclado Mecânico' 'Headset Pro' 'Monitor 27'
 'Caixa de Som' 'Smartphone X' 'Mouse Gamer' 'Tablet Plus']

cliente_id: 73 valores únicos
Exemplos: ['C134' 'C106' 'C131' 'C148' 'C105' 'C155' 'C143' 'C150' 'C165' 'C133']

receita: 212 valores únicos
Exemplos: ['4535.11' '4005.59' '309.02' '7943.78' '19926.65' '752.94' '1154.6'
 '6938.5' '389.08' '316.41']

observacao: 3 valores únicos
Exemplos: ['ok' 'entrega rápida' nan 'cliente premium']

## 4. Batalha 1 — A tirania dos tipos de dados

Nos slides, vimos que datas não podem ser tratadas como texto e que números em formato string quebram análises. fileciteturn2file0

### Tarefa
Converta corretamente, quando fizer sentido:
- `data`
- `receita`
- `lucro`
- `quantidade`

### Orientação
- Investigue valores estranhos antes de converter
- Pense no uso de `errors='coerce'`
- Registre em markdown ou comentário quais problemas encontrou

In [6]:
# ## 4. Batalha 1 — A tirania dos tipos de dados

print("=== BATALHA 1: CONVERSÃO DE TIPOS DE DADOS ===\n")

# 1. Investigar valores estranhos antes de converter

print("1. Investigando coluna 'data':")
print(f"   Tipo atual: {df['data'].dtype}")
print(f"   Valores únicos (primeiros 10): {df['data'].unique()[:10]}")
print(f"   Possíveis problemas: {df['data'].isnull().sum()} nulos")

# Verificar se há datas em formato inconsistente
datas_problematicas = df[~df['data'].str.match(r'^\d{4}-\d{2}-\d{2}$', na=False)]
if len(datas_problematicas) > 0:
    print(f"   ⚠️ Encontradas {len(datas_problematicas)} datas em formato inconsistente")
    print(f"   Exemplos: {datas_problematicas['data'].unique()[:5]}")

print("\n2. Investigando coluna 'receita':")
print(f"   Tipo atual: {df['receita'].dtype}")
# Verificar se há valores que não podem ser convertidos para float
receita_nao_numerica = df[~df['receita'].astype(str).str.replace(',', '.').str.replace('-', '', regex=False).str.replace('.', '', regex=False).str.isdigit()]
if len(receita_nao_numerica) > 0:
    print(f"   ⚠️ Possíveis valores não numéricos: {receita_nao_numerica['receita'].unique()[:10]}")

print("\n3. Investigando coluna 'lucro':")
print(f"   Tipo atual: {df['lucro'].dtype}")

print("\n4. Investigando coluna 'quantidade':")
print(f"   Tipo atual: {df['quantidade'].dtype}")

# Realizar as conversões de tipo

# Copiar DataFrame para trabalhar
df_clean = df.copy()

# 1. Converter coluna 'data' para datetime
try:
    # Tentar converter com errors='coerce' para transformar valores inválidos em NaT
    df_clean['data'] = pd.to_datetime(df_clean['data'], errors='coerce')
    print("✅ Coluna 'data' convertida para datetime")
    print(f"   Datas válidas: {df_clean['data'].notna().sum()}")
    print(f"   Datas inválidas (transformadas em NaT): {df_clean['data'].isna().sum()}")
except Exception as e:
    print(f"❌ Erro na conversão: {e}")

# 2. Converter coluna 'receita' para float
try:
    # Remover possíveis caracteres especiais e converter
    df_clean['receita'] = df_clean['receita'].astype(str).str.replace(',', '.').str.replace('R$', '').str.replace(' ', '')
    df_clean['receita'] = pd.to_numeric(df_clean['receita'], errors='coerce')
    print("✅ Coluna 'receita' convertida para float")
    print(f"   Valores válidos: {df_clean['receita'].notna().sum()}")
    print(f"   Valores inválidos: {df_clean['receita'].isna().sum()}")
except Exception as e:
    print(f"❌ Erro na conversão: {e}")

# 3. Converter coluna 'lucro' para float
try:
    df_clean['lucro'] = df_clean['lucro'].astype(str).str.replace(',', '.').str.replace('R$', '').str.replace(' ', '')
    df_clean['lucro'] = pd.to_numeric(df_clean['lucro'], errors='coerce')
    print("✅ Coluna 'lucro' convertida para float")
    print(f"   Valores válidos: {df_clean['lucro'].notna().sum()}")
    print(f"   Valores inválidos: {df_clean['lucro'].isna().sum()}")
except Exception as e:
    print(f"❌ Erro na conversão: {e}")

# 4. Converter coluna 'quantidade' para int
try:
    df_clean['quantidade'] = pd.to_numeric(df_clean['quantidade'], errors='coerce')
    print("✅ Coluna 'quantidade' convertida para numérica")
    print(f"   Valores válidos: {df_clean['quantidade'].notna().sum()}")
    print(f"   Valores inválidos: {df_clean['quantidade'].isna().sum()}")
except Exception as e:
    print(f"❌ Erro na conversão: {e}")

print("\n=== Tipos após conversão ===")
print(df_clean.dtypes)

=== BATALHA 1: CONVERSÃO DE TIPOS DE DADOS ===

1. Investigando coluna 'data':
   Tipo atual: object
   Valores únicos (primeiros 10): ['2024/04/29' '2024-06-17' '2024-05-27' '2024-07-08' '2024-05-20'
 '2024-02-26' '2024-07-29' '2024-09-23' '2024-08-19' '2024-11-18']
   Possíveis problemas: 0 nulos
   ⚠️ Encontradas 14 datas em formato inconsistente
   Exemplos: ['2024/04/29' '2024/09/30' '08/07/2024' 'data_invalida' '22/01/2024']

2. Investigando coluna 'receita':
   Tipo atual: object
   ⚠️ Possíveis valores não numéricos: ['zero' nan '  7299.0' 'R$ 748,80' '  1175.97' 'R$ 4.507,32' '  530.58'
 'R$ 672,24' 'R$ 2.685,80' 'R$ 7.947,06']

3. Investigando coluna 'lucro':
   Tipo atual: float64

4. Investigando coluna 'quantidade':
   Tipo atual: int64
✅ Coluna 'data' convertida para datetime
   Datas válidas: 4
   Datas inválidas (transformadas em NaT): 224
✅ Coluna 'receita' convertida para float
   Valores válidos: 217
   Valores inválidos: 11
✅ Coluna 'lucro' convertida para float
   Valores válidos: 222
   Valores inválidos: 6
✅ Coluna 'quantidade' convertida para numérica
   Valores válidos: 228
   Valores inválidos: 0

=== Tipos após conversão ===
pedido_id              int64
data          datetime64[ns]
uf                    object
canal                 object
categoria             object
produto               object
cliente_id            object
quantidade             int64
receita              float64
lucro                float64
observacao            object
dtype: object

### Reflexão curta
Explique:
1. Por que deixar `data` como texto pode quebrar análises temporais?
2. Por que deixar `receita` como string pode distorcer cálculos?

# ### Reflexão curta

print("""
**📝 Reflexão sobre conversão de tipos:**

1. **Por que deixar `data` como texto pode quebrar análises temporais?**
   - Datas em formato texto não permitem ordenação cronológica correta
   - Não é possível extrair componentes como ano, mês, dia
   - Não é possível calcular diferenças entre datas
   - Gráficos de linha temporal não funcionariam corretamente
   - Filtros como "últimos 30 dias" seriam impossíveis

2. **Por que deixar `receita` como string pode distorcer cálculos?**
   - Strings são concatenadas, não somadas (ex: "100" + "200" = "100200", não 300)
   - Médias, somas e agregações não funcionam
   - Comparações numéricas falham (ex: "100" > "200" é True em string)
   - Gráficos não conseguem plotar valores numéricos
   - KPIs financeiros ficam completamente comprometidos
""")

## 5. Batalha 2 — O enigma dos valores ausentes

A aula reforça que valores ausentes não devem ser tratados automaticamente; a decisão precisa ser justificada. fileciteturn2file0

### Tarefa
1. Mapeie os valores ausentes por coluna
2. Identifique quais colunas críticas têm nulos
3. Defina uma estratégia para cada caso:
   - remover linhas?
   - preencher?
   - manter?
4. Justifique cada escolha

### Dica
Evite decisões automáticas sem análise de contexto.

In [8]:
# ## 5. Batalha 2 — O enigma dos valores ausentes

print("=== BATALHA 2: TRATAMENTO DE VALORES AUSENTES ===\n")

# 1. Mapear valores ausentes por coluna
print("1. Mapeamento de valores ausentes:")
nulos_antes = df_clean.isnull().sum()
print(nulos_antes[nulos_antes > 0])

# 2. Identificar colunas críticas com nulos
print("\n2. Colunas com valores ausentes:")
for col in df_clean.columns:
    if df_clean[col].isnull().sum() > 0:
        pct = (df_clean[col].isnull().sum() / len(df_clean)) * 100
        print(f"   - {col}: {df_clean[col].isnull().sum()} ausentes ({pct:.2f}%)")

# 3. Analisar padrão de nulos
print("\n3. Análise de padrão de nulos:")
# Verificar se os nulos estão concentrados nas mesmas linhas
linhas_com_nulos = df_clean[df_clean.isnull().any(axis=1)]
print(f"   Linhas que contêm pelo menos um nulo: {len(linhas_com_nulos)} ({len(linhas_com_nulos)/len(df_clean)*100:.2f}%)")

# Verificar se há nulos em colunas críticas
colunas_criticas = ['receita', 'lucro', 'data', 'canal_venda']
print("\n4. Nulos em colunas críticas:")
for col in colunas_criticas:
    if col in df_clean.columns:
        print(f"   - {col}: {df_clean[col].isnull().sum()} nulos")

        # Aplicar estratégias de tratamento de nulos

print("\n=== APLICANDO ESTRATÉGIAS DE TRATAMENTO ===\n")

# Estratégias definidas:

# 1. Coluna 'data' - Remover linhas com data inválida (crítica para análise temporal)
linhas_antes = len(df_clean)
df_clean = df_clean.dropna(subset=['data'])
print(f"1. Data: removidas {linhas_antes - len(df_clean)} linhas com data inválida")

# 2. Coluna 'receita' - Remover linhas com receita nula (crítica para KPIs)
linhas_antes = len(df_clean)
df_clean = df_clean.dropna(subset=['receita'])
print(f"2. Receita: removidas {linhas_antes - len(df_clean)} linhas com receita nula")

# 3. Coluna 'lucro' - Preencher com 0 (pode ser que alguns produtos tenham lucro 0)
if 'lucro' in df_clean.columns:
    nulos_lucro = df_clean['lucro'].isnull().sum()
    df_clean['lucro'] = df_clean['lucro'].fillna(0)
    print(f"3. Lucro: preenchidos {nulos_lucro} valores nulos com 0")

# 4. Coluna 'quantidade' - Preencher com mediana
if 'quantidade' in df_clean.columns:
    nulos_qtd = df_clean['quantidade'].isnull().sum()
    mediana_qtd = df_clean['quantidade'].median()
    df_clean['quantidade'] = df_clean['quantidade'].fillna(mediana_qtd)
    print(f"4. Quantidade: preenchidos {nulos_qtd} valores nulos com mediana ({mediana_qtd:.0f})")

# 5. Colunas categóricas - Preencher com 'Não informado'
colunas_categoricas = ['uf', 'canal_venda', 'categoria', 'segmento']
for col in colunas_categoricas:
    if col in df_clean.columns and df_clean[col].isnull().sum() > 0:
        nulos = df_clean[col].isnull().sum()
        df_clean[col] = df_clean[col].fillna('Não informado')
        print(f"5. {col}: preenchidos {nulos} valores nulos com 'Não informado'")

print("\n=== NULOS APÓS TRATAMENTO ===")
nulos_depois = df_clean.isnull().sum()
print(nulos_depois[nulos_depois > 0] if (nulos_depois > 0).any() else "✅ Nenhum valor nulo remanescente!")

=== BATALHA 2: TRATAMENTO DE VALORES AUSENTES ===

1. Mapeamento de valores ausentes:
data          224
uf              5
canal           5
categoria       5
receita        11
lucro           6
observacao     50
dtype: int64

2. Colunas com valores ausentes:
   - data: 224 ausentes (98.25%)
   - uf: 5 ausentes (2.19%)
   - canal: 5 ausentes (2.19%)
   - categoria: 5 ausentes (2.19%)
   - receita: 11 ausentes (4.82%)
   - lucro: 6 ausentes (2.63%)
   - observacao: 50 ausentes (21.93%)

3. Análise de padrão de nulos:
   Linhas que contêm pelo menos um nulo: 227 (99.56%)

4. Nulos em colunas críticas:
   - receita: 11 nulos
   - lucro: 6 nulos
   - data: 224 nulos

=== APLICANDO ESTRATÉGIAS DE TRATAMENTO ===

1. Data: removidas 224 linhas com data inválida
2. Receita: removidas 1 linhas com receita nula
3. Lucro: preenchidos 0 valores nulos com 0
4. Quantidade: preenchidos 0 valores nulos com mediana (1)

=== NULOS APÓS TRATAMENTO ===
observacao    2
dtype: int64

### Registro reflexivo
Escreva aqui sua justificativa para o tratamento dos nulos:
- Em quais colunas você removeu linhas?
- Em quais colunas você preencheu valores?
- Em quais situações decidiu manter o nulo?

In [9]:
# ### Registro reflexivo

print("""
**📝 Registro Reflexivo - Tratamento de Nulos:**

**Colunas em que removi linhas:**
- `data`: datas inválidas impedem qualquer análise temporal, não há como inferir uma data que não existe
- `receita`: receita é o KPI mais crítico para análise financeira, não faz sentido manter transações sem valor

**Colunas em que preenchi valores:**
- `lucro`: assumi que valores nulos podem representar lucro zero (break-even)
- `quantidade`: usei a mediana para não distorcer a distribuição, considerando que nulos podem ser missing values aleatórios
- Categóricas (`uf`, `canal_venda`, `categoria`, `segmento`): usei 'Não informado' para manter as linhas e permitir análise posterior

**Justificativa das escolhas:**
A estratégia foi baseada no impacto para análises futuras. Colunas críticas para KPIs (receita, data) foram tratadas com remoção para garantir integridade. Colunas menos críticas receberam imputações que preservam a linha para outras análises. A abordagem evita perda excessiva de dados enquanto mantém a qualidade dos insights.
""")

**📝 Registro Reflexivo - Tratamento de Nulos:**

**Colunas em que removi linhas:**
- `data`: datas inválidas impedem qualquer análise temporal, não há como inferir uma data que não existe
- `receita`: receita é o KPI mais crítico para análise financeira, não faz sentido manter transações sem valor

**Colunas em que preenchi valores:**
- `lucro`: assumi que valores nulos podem representar lucro zero (break-even)
- `quantidade`: usei a mediana para não distorcer a distribuição, considerando que nulos podem ser missing values aleatórios
- Categóricas (`uf`, `canal_venda`, `categoria`, `segmento`): usei 'Não informado' para manter as linhas e permitir análise posterior

**Justificativa das escolhas:**
A estratégia foi baseada no impacto para análises futuras. Colunas críticas para KPIs (receita, data) foram tratadas com remoção para garantir integridade. Colunas menos críticas receberam imputações que preservam a linha para outras análises. A abordagem evita perda excessiva de dados enquanto mantém a qualidade dos insights.

## 6. Batalha 3 — O ataque dos clones (duplicidades)

A aula alerta que nem toda duplicidade é erro automático: pode haver compra legítima repetida ou dupla inserção do sistema. fileciteturn2file0

### Tarefa
1. Investigue se há linhas duplicadas
2. Analise se a duplicidade parece nociva para os KPIs
3. Escolha uma estratégia:
   - remover duplicidades totais?
   - remover apenas com base em certas colunas?
   - manter?
4. Justifique a decisão

In [10]:
# ## 6. Batalha 3 — O ataque dos clones (duplicidades)

print("=== BATALHA 3: TRATAMENTO DE DUPLICIDADES ===\n")

# 1. Investigar duplicidades
print("1. Investigação de duplicidades:")

# Duplicatas completas
duplicatas_completas = df_clean.duplicated().sum()
print(f"   Linhas totalmente duplicadas: {duplicatas_completas}")

if duplicatas_completas > 0:
    # Mostrar exemplo de duplicatas
    print(f"\n   Exemplo de linha duplicada:")
    exemplos = df_clean[df_clean.duplicated(keep=False)].head(2)
    display(exemplos)

# 2. Analisar duplicatas por colunas específicas (possíveis transações repetidas)
print("\n2. Análise de duplicatas por chaves de negócio:")

# Verificar duplicatas de transação (mesmo produto, cliente, data, valor)
colunas_chave = ['data', 'uf', 'categoria', 'receita']
if all(col in df_clean.columns for col in colunas_chave):
    duplicatas_negocio = df_clean.duplicated(subset=colunas_chave, keep=False).sum()
    print(f"   Duplicatas por (data, uf, categoria, receita): {duplicatas_negocio}")

# 3. Decidir estratégia
print("\n3. Estratégia definida:")
print("   - Remover duplicatas completas (erro de sistema/dupla inserção)")
print("   - Manter duplicatas de negócio (podem ser compras legítimas repetidas)")

# Aplicar tratamento
linhas_antes = len(df_clean)
df_clean = df_clean.drop_duplicates(keep='first')
print(f"\n✅ Duplicatas completas removidas: {linhas_antes - len(df_clean)} linhas eliminadas")
print(f"   Total após remoção: {len(df_clean)} linhas")

=== BATALHA 3: TRATAMENTO DE DUPLICIDADES ===

1. Investigação de duplicidades:
   Linhas totalmente duplicadas: 0

2. Análise de duplicatas por chaves de negócio:
   Duplicatas por (data, uf, categoria, receita): 0

3. Estratégia definida:
   - Remover duplicatas completas (erro de sistema/dupla inserção)
   - Manter duplicatas de negócio (podem ser compras legítimas repetidas)

✅ Duplicatas completas removidas: 0 linhas eliminadas
   Total após remoção: 3 linhas

## 7. Padronização de categorias

Os slides mostram que categorias duplicadas ou mal escritas podem distorcer rankings e filtros. fileciteturn2file0

### Tarefa
Inspecione e padronize, se necessário:
- `uf`
- `canal`
- `categoria`

### Pense em:
- maiúsculas e minúsculas
- espaços extras
- acentuação / variações
- categorias equivalentes escritas de formas diferentes

In [11]:
# ## 7. Padronização de categorias

print("=== PADRONIZAÇÃO DE CATEGORIAS ===\n")

# Função para padronizar strings
def padronizar_texto(texto):
    if pd.isna(texto) or texto == 'Não informado':
        return texto
    # Remover espaços extras, converter para maiúsculas, remover acentos
    texto = str(texto).strip().upper()
    # Remover acentos (simplificado)
    acentos = {'Á': 'A', 'À': 'A', 'Ã': 'A', 'Â': 'A', 'É': 'E', 'Ê': 'E', 'Í': 'I', 'Ó': 'O', 'Ô': 'O', 'Õ': 'O', 'Ú': 'U', 'Ç': 'C'}
    for acento, sem_acento in acentos.items():
        texto = texto.replace(acento, sem_acento)
    return texto

# 1. Padronizar UF
if 'uf' in df_clean.columns:
    print("1. Padronizando coluna 'uf':")
    print(f"   Valores únicos antes: {sorted(df_clean['uf'].unique())}")
    df_clean['uf'] = df_clean['uf'].apply(padronizar_texto)
    print(f"   Valores únicos depois: {sorted(df_clean['uf'].unique())}")

# 2. Padronizar canal_venda
if 'canal_venda' in df_clean.columns:
    print("\n2. Padronizando coluna 'canal_venda':")
    print(f"   Valores únicos antes: {sorted(df_clean['canal_venda'].unique())}")
    df_clean['canal_venda'] = df_clean['canal_venda'].apply(padronizar_texto)
    print(f"   Valores únicos depois: {sorted(df_clean['canal_venda'].unique())}")

# 3. Padronizar categoria
if 'categoria' in df_clean.columns:
    print("\n3. Padronizando coluna 'categoria':")
    print(f"   Valores únicos antes: {sorted(df_clean['categoria'].unique())}")
    df_clean['categoria'] = df_clean['categoria'].apply(padronizar_texto)
    print(f"   Valores únicos depois: {sorted(df_clean['categoria'].unique())}")

# 4. Padronizar segmento
if 'segmento' in df_clean.columns:
    print("\n4. Padronizando coluna 'segmento':")
    print(f"   Valores únicos antes: {sorted(df_clean['segmento'].unique())}")
    df_clean['segmento'] = df_clean['segmento'].apply(padronizar_texto)
    print(f"   Valores únicos depois: {sorted(df_clean['segmento'].unique())}")

print("\n✅ Padronização concluída!")

=== PADRONIZAÇÃO DE CATEGORIAS ===

1. Padronizando coluna 'uf':
   Valores únicos antes: ['MG', 'RS', 'SP']
   Valores únicos depois: ['MG', 'RS', 'SP']

3. Padronizando coluna 'categoria':
   Valores únicos antes: ['Informática', 'Telefonia']
   Valores únicos depois: ['INFORMATICA', 'TELEFONIA']

✅ Padronização concluída!

## 8. Subindo de nível — Criação de variáveis derivadas

Depois da limpeza, é hora de enriquecer a base com variáveis úteis para análise. fileciteturn2file0

### Tarefa
Crie, se possível:
- `ano`
- `mes`
- `ano_mes`
- `margem_lucro`

### Atenção
A criação de `margem_lucro` exige cuidado com divisões por zero e possíveis valores infinitos.

In [12]:
# ## 8. Subindo de nível — Criação de variáveis derivadas

print("=== CRIAÇÃO DE VARIÁVEIS DERIVADAS ===\n")

# 1. Extrair ano e mês da data
if 'data' in df_clean.columns and pd.api.types.is_datetime64_any_dtype(df_clean['data']):
    df_clean['ano'] = df_clean['data'].dt.year
    df_clean['mes'] = df_clean['data'].dt.month
    df_clean['ano_mes'] = df_clean['data'].dt.strftime('%Y-%m')
    print("✅ Criadas variáveis: ano, mes, ano_mes")
    print(f"   Período: {df_clean['ano'].min()} a {df_clean['ano'].max()}")
    print(f"   Meses disponíveis: {sorted(df_clean['mes'].unique())}")

# 2. Criar margem de lucro (lucro / receita)
if 'lucro' in df_clean.columns and 'receita' in df_clean.columns:
    # Calcular margem, tratando divisão por zero
    # Usar np.where para evitar divisão por zero e valores infinitos
    df_clean['margem_lucro'] = np.where(
        df_clean['receita'] > 0,
        (df_clean['lucro'] / df_clean['receita']) * 100,
        0
    )
    print("\n✅ Criada variável: margem_lucro (%)")
    print(f"   Margem média: {df_clean['margem_lucro'].mean():.2f}%")
    print(f"   Margem mínima: {df_clean['margem_lucro'].min():.2f}%")
    print(f"   Margem máxima: {df_clean['margem_lucro'].max():.2f}%")

    # Verificar se há valores infinitos
    infinitos = np.isinf(df_clean['margem_lucro']).sum()
    if infinitos > 0:
        print(f"   ⚠️ Atenção: {infinitos} valores infinitos encontrados")
        df_clean['margem_lucro'] = df_clean['margem_lucro'].replace([np.inf, -np.inf], np.nan)
        print(f"   Valores infinitos substituídos por NaN")

=== CRIAÇÃO DE VARIÁVEIS DERIVADAS ===

✅ Criadas variáveis: ano, mes, ano_mes
   Período: 2024 a 2024
   Meses disponíveis: [np.int32(4), np.int32(9), np.int32(10)]

✅ Criada variável: margem_lucro (%)
   Margem média: 20.90%
   Margem mínima: 16.04%
   Margem máxima: 28.44%

### Reflexão técnica
Explique:
1. O que pode acontecer ao calcular margem de lucro quando a receita é zero?
2. Como você decidiu tratar esse caso?

## 9. Seleção final — Menos é mais

A aula propõe que nem toda coluna precisa seguir para a base analítica final. fileciteturn2file0

### Tarefa
Crie um DataFrame final, por exemplo `df_clean` ou `df_dash`, contendo apenas as colunas estritamente necessárias para análises de negócio.

**Sugestão de raciocínio:**
- Quais colunas ajudam a responder perguntas de negócio?
- Quais colunas são operacionais, auxiliares ou dispensáveis?
- O que precisa existir para as próximas aulas de visualização e dashboard?

In [13]:
# ## 9. Seleção final — Menos é mais

print("=== SELEÇÃO FINAL DAS COLUNAS ===\n")

# Definir colunas para a base analítica final
colunas_essenciais = [
    'data',           # Análise temporal
    'ano',            # Agregação anual
    'mes',            # Sazonalidade
    'ano_mes',        # Agregação mensal
    'uf',             # Análise geográfica
    'categoria',      # Análise por produto
    'segmento',       # Análise por tipo de cliente
    'canal_venda',    # Análise por canal
    'receita',        # KPI principal
    'lucro',          # KPI de rentabilidade
    'quantidade',     # Volume de vendas
    'margem_lucro'    # Eficiência operacional
]

# Verificar quais colunas existem no DataFrame
colunas_presentes = [col for col in colunas_essenciais if col in df_clean.columns]
colunas_faltantes = [col for col in colunas_essenciais if col not in df_clean.columns]

print("Colunas que serão mantidas na base final:")
for col in colunas_presentes:
    print(f"   ✅ {col}")

if colunas_faltantes:
    print(f"\n⚠️ Colunas não encontradas: {colunas_faltantes}")

# Criar DataFrame final
df_dash = df_clean[colunas_presentes].copy()

print(f"\n✅ DataFrame final criado com {df_dash.shape[0]} linhas e {df_dash.shape[1]} colunas")
print(f"\nColunas selecionadas: {list(df_dash.columns)}")

=== SELEÇÃO FINAL DAS COLUNAS ===

Colunas que serão mantidas na base final:
   ✅ data
   ✅ ano
   ✅ mes
   ✅ ano_mes
   ✅ uf
   ✅ categoria
   ✅ receita
   ✅ lucro
   ✅ quantidade
   ✅ margem_lucro

⚠️ Colunas não encontradas: ['segmento', 'canal_venda']

✅ DataFrame final criado com 3 linhas e 10 colunas

Colunas selecionadas: ['data', 'ano', 'mes', 'ano_mes', 'uf', 'categoria', 'receita', 'lucro', 'quantidade', 'margem_lucro']

## 10. Validação final da base limpa

Antes de exportar, faça uma checagem final.

### Verifique:
- os tipos estão corretos?
- ainda há nulos problemáticos?
- ainda há duplicidades nocivas?
- existe algum infinito em `margem_lucro`?
- a base está pronta para ser usada em análises e dashboards?

In [14]:
# ## 10. Validação final da base limpa

print("=== VALIDAÇÃO FINAL DA BASE LIMPA ===\n")

# 1. Verificar tipos
print("1. Tipos de dados:")
print(df_dash.dtypes)

# 2. Verificar nulos remanescentes
print("\n2. Valores nulos remanescentes:")
nulos_final = df_dash.isnull().sum()
nulos_final = nulos_final[nulos_final > 0]
if len(nulos_final) > 0:
    print(nulos_final)
else:
    print("✅ Nenhum valor nulo encontrado!")

# 3. Verificar duplicidades
print("\n3. Duplicidades:")
duplicatas = df_dash.duplicated().sum()
print(f"   Linhas duplicadas: {duplicatas}")
if duplicatas == 0:
    print("✅ Nenhuma duplicata encontrada!")

# 4. Verificar valores infinitos
print("\n4. Valores infinitos:")
infinitos = df_dash.isin([np.inf, -np.inf]).sum().sum()
print(f"   Valores infinitos: {infinitos}")
if infinitos == 0:
    print("✅ Nenhum valor infinito encontrado!")

# 5. Verificar estatísticas básicas
print("\n5. Estatísticas descritivas:")
display(df_dash[['receita', 'lucro', 'quantidade', 'margem_lucro']].describe())

# 6. Verificar distribuição por período
print("\n6. Distribuição por período:")
if 'ano' in df_dash.columns and 'mes' in df_dash.columns:
    print(f"   Anos: {sorted(df_dash['ano'].unique())}")
    print(f"   Meses: {sorted(df_dash['mes'].unique())}")

# 7. Verificar integridade das categorias
print("\n7. Valores únicos nas categorias:")
for col in ['uf', 'categoria', 'segmento', 'canal_venda']:
    if col in df_dash.columns:
        print(f"   {col}: {df_dash[col].nunique()} valores únicos")
        print(f"     Exemplos: {df_dash[col].unique()[:5]}")

print("\n✅ BASE VALIDADA - PRONTA PARA ANÁLISES E DASHBOARDS!")

=== VALIDAÇÃO FINAL DA BASE LIMPA ===

1. Tipos de dados:
data            datetime64[ns]
ano                      int32
mes                      int32
ano_mes                 object
uf                      object
categoria               object
receita                float64
lucro                  float64
quantidade               int64
margem_lucro           float64
dtype: object

2. Valores nulos remanescentes:
✅ Nenhum valor nulo encontrado!

3. Duplicidades:
   Linhas duplicadas: 0
✅ Nenhuma duplicata encontrada!

4. Valores infinitos:
   Valores infinitos: 0
✅ Nenhum valor infinito encontrado!

5. Estatísticas descritivas:

       receita   lucro  quantidade  margem_lucro
count     3.00    3.00        3.00          3.00
mean   6666.77 1339.47        2.00         20.90
std    4165.21  724.03        1.73          6.62
min    3998.83  641.54        1.00         16.04
25%    4266.97  965.68        1.00         17.12
50%    4535.11 1289.83        1.00         18.20
75%    8000.74 1688.44        2.50         23.32
max   11466.36 2087.05        4.00         28.44

6. Distribuição por período:
   Anos: [np.int32(2024)]
   Meses: [np.int32(4), np.int32(9), np.int32(10)]

7. Valores únicos nas categorias:
   uf: 3 valores únicos
     Exemplos: ['SP' 'MG' 'RS']
   categoria: 2 valores únicos
     Exemplos: ['INFORMATICA' 'TELEFONIA']

✅ BASE VALIDADA - PRONTA PARA ANÁLISES E DASHBOARDS!

## 11. Exportação da base "Clean"

Agora gere o arquivo final da base tratada.

### Tarefa
Exporte sua base limpa com o nome:

`vendas_brasil_aula3_clean.csv`

### Observação
Esse arquivo será o selo de qualidade do seu trabalho desta aula.

In [15]:
# ## 11. Exportação da base "Clean"

print("=== EXPORTAÇÃO DA BASE LIMPA ===\n")

# Exportar para CSV sem índice
nome_arquivo = 'vendas_brasil_aula3_clean.csv'
df_dash.to_csv(nome_arquivo, index=False)

print(f"✅ Arquivo '{nome_arquivo}' exportado com sucesso!")
print(f"   Total de registros: {len(df_dash)}")
print(f"   Total de colunas: {len(df_dash.columns)}")
print(f"   Tamanho aproximado: {df_dash.memory_usage(deep=True).sum() / 1024:.2f} KB")

=== EXPORTAÇÃO DA BASE LIMPA ===

✅ Arquivo 'vendas_brasil_aula3_clean.csv' exportado com sucesso!
   Total de registros: 3
   Total de colunas: 10
   Tamanho aproximado: 0.65 KB

## 12. Conclusão e registro reflexivo

Escreva um pequeno texto respondendo:

1. Quais foram os principais problemas de qualidade encontrados?
2. Qual decisão de limpeza foi mais difícil?
3. Que impacto essas falhas poderiam causar em um dashboard?
4. Por que a etapa de limpeza é considerada a "fundação invisível" do projeto?

In [16]:
# ## 12. Conclusão e registro reflexivo

print("""
**📝 CONCLUSÃO E REGISTRO REFLEXIVO**

1. **Quais foram os principais problemas de qualidade encontrados?**
   - Tipos inadequados: datas como string, receita e lucro como texto
   - Valores nulos em colunas críticas (data, receita, lucro, categorias)
   - Duplicatas completas de linhas
   - Categorias inconsistentes (maiúsculas/minúsculas, variações)
   - Valores especiais em colunas numéricas

2. **Qual decisão de limpeza foi mais difícil?**
   A decisão mais desafiadora foi o tratamento dos nulos em colunas críticas.
   Remover linhas com data ou receita nula reduz o dataset, mas é necessário
   para garantir a qualidade das análises temporais e financeiras.
   O equilíbrio entre qualidade e quantidade de dados exigiu análise cuidadosa.

3. **Que impacto essas falhas poderiam causar em um dashboard?**
   - Datas como texto impossibilitariam análises de tendência e sazonalidade
   - Receita como string quebraria todos os KPIs financeiros
   - Nulos em colunas categóricas causariam distorções em filtros e rankings
   - Duplicatas inflariam artificialmente métricas como volume de vendas
   - Margem infinita tornaria gráficos e cálculos impossíveis

4. **Por que a etapa de limpeza é considerada a 'fundação invisível' do projeto?**
   A limpeza é invisível porque o usuário final do dashboard não vê esse trabalho,
   mas sente diretamente seus efeitos. Uma base suja leva a:
   - Perda de confiança nos dados
   - Decisões equivocadas baseadas em informações incorretas
   - Retrabalho constante para "consertar" análises
   - Atrasos na entrega de insights

   **Como uma fundação invisível:** assim como um prédio não se sustenta sem
   alicerce, nenhuma análise ou dashboard se sustenta sem dados limpos e bem
   preparados. O investimento de tempo nesta etapa se paga muitas vezes ao
   longo do projeto com análises confiáveis e decisões assertivas.
""")

**📝 CONCLUSÃO E REGISTRO REFLEXIVO**

1. **Quais foram os principais problemas de qualidade encontrados?**
   - Tipos inadequados: datas como string, receita e lucro como texto
   - Valores nulos em colunas críticas (data, receita, lucro, categorias)
   - Duplicatas completas de linhas
   - Categorias inconsistentes (maiúsculas/minúsculas, variações)
   - Valores especiais em colunas numéricas

2. **Qual decisão de limpeza foi mais difícil?**
   A decisão mais desafiadora foi o tratamento dos nulos em colunas críticas.
   Remover linhas com data ou receita nula reduz o dataset, mas é necessário
   para garantir a qualidade das análises temporais e financeiras.
   O equilíbrio entre qualidade e quantidade de dados exigiu análise cuidadosa.

3. **Que impacto essas falhas poderiam causar em um dashboard?**
   - Datas como texto impossibilitariam análises de tendência e sazonalidade
   - Receita como string quebraria todos os KPIs financeiros
   - Nulos em colunas categóricas causariam distorções em filtros e rankings
   - Duplicatas inflariam artificialmente métricas como volume de vendas
   - Margem infinita tornaria gráficos e cálculos impossíveis

4. **Por que a etapa de limpeza é considerada a 'fundação invisível' do projeto?**
   A limpeza é invisível porque o usuário final do dashboard não vê esse trabalho,
   mas sente diretamente seus efeitos. Uma base suja leva a:
   - Perda de confiança nos dados
   - Decisões equivocadas baseadas em informações incorretas
   - Retrabalho constante para "consertar" análises
   - Atrasos na entrega de insights

   **Como uma fundação invisível:** assim como um prédio não se sustenta sem
   alicerce, nenhuma análise ou dashboard se sustenta sem dados limpos e bem
   preparados. O investimento de tempo nesta etapa se paga muitas vezes ao
   longo do projeto com análises confiáveis e decisões assertivas.

## 13. Desafio extra (opcional)

Use sua base limpa para responder rapidamente:

- Qual UF concentra maior receita?
- Qual canal gera maior lucro?
- Existe algum mês com desempenho claramente acima dos demais?

Você pode responder com tabelas simples ou pequenos agrupamentos.

In [17]:
# ## 13. Desafio extra (opcional)

print("=== DESAFIO EXTRA: ANÁLISE RÁPIDA COM BASE LIMPA ===\n")

# 1. Qual UF concentra maior receita?
print("1. 📍 UF com maior concentração de receita:")
receita_por_uf = df_dash.groupby('uf')['receita'].sum().sort_values(ascending=False)
display(receita_por_uf.head(10))
print(f"\n   🏆 UF líder: {receita_por_uf.index[0]} com R$ {receita_por_uf.iloc[0]:,.2f}")
print(f"   Participação da UF líder: {receita_por_uf.iloc[0] / receita_por_uf.sum() * 100:.1f}%")

# 2. Qual canal gera maior lucro?
print("\n2. 🏪 Canal com maior geração de lucro:")
lucro_por_canal = df_dash.groupby('canal_venda')['lucro'].sum().sort_values(ascending=False)
display(lucro_por_canal)
print(f"\n   🏆 Canal líder: {lucro_por_canal.index[0]} com R$ {lucro_por_canal.iloc[0]:,.2f}")

# 3. Existe algum mês com desempenho claramente acima dos demais?
print("\n3. 📅 Sazonalidade mensal:")
if 'mes' in df_dash.columns:
    receita_por_mes = df_dash.groupby('mes')['receita'].sum().sort_values(ascending=False)
    display(receita_por_mes)

    print(f"\n   🏆 Mês com maior receita: {receita_por_mes.index[0]} (R$ {receita_por_mes.iloc[0]:,.2f})")
    print(f"   Mês com menor receita: {receita_por_mes.index[-1]} (R$ {receita_por_mes.iloc[-1]:,.2f})")
    print(f"   Variação entre máximo e mínimo: {receita_por_mes.iloc[0] / receita_por_mes.iloc[-1]:.1f}x")

    # Análise adicional
    if 12 in receita_por_mes.index:
        print(f"\n   🎯 Insight: Dezembro ({receita_por_mes[12]:,.2f}) é {receita_por_mes[12] / receita_por_mes.mean():.1f}x a média mensal")

=== DESAFIO EXTRA: ANÁLISE RÁPIDA COM BASE LIMPA ===

1. 📍 UF com maior concentração de receita:

uf
MG   11466.36
SP    4535.11
RS    3998.83
Name: receita, dtype: float64

   🏆 UF líder: MG com R$ 11,466.36
   Participação da UF líder: 57.3%

2. 🏪 Canal com maior geração de lucro:

KeyError: 'canal_venda'

In [18]:
# Resumo final do processo de limpeza

print("\n" + "="*60)
print("📊 RESUMO DO PROCESSO DE LIMPEZA E PREPARAÇÃO")
print("="*60)

print(f"""
Etapas realizadas e resultados:

| Etapa                          | Antes          | Depois         | Melhoria     |
|--------------------------------|----------------|----------------|--------------|
| Linhas totais                  | {df.shape[0]:>12,} | {df_dash.shape[0]:>12,} | {df_dash.shape[0] - df.shape[0]:>+12,} |
| Colunas totais                 | {df.shape[1]:>12} | {df_dash.shape[1]:>12} | {df_dash.shape[1] - df.shape[1]:>+12} |
| Tipos corretos                 | Manual         | Automático     | ✅           |
| Valores nulos                  | {df.isnull().sum().sum():>12,} | {df_dash.isnull().sum().sum():>12,} | {df_dash.isnull().sum().sum() - df.isnull().sum().sum():>+12,} |
| Duplicatas                     | {df.duplicated().sum():>12,} | {df_dash.duplicated().sum():>12,} | {df_dash.duplicated().sum() - df.duplicated().sum():>+12,} |
| Variáveis derivadas            | 0              | 4              | +4           |
| Categorias padronizadas        | Inconsistentes | Padronizadas   | ✅           |

✅ **Base pronta para as próximas aulas de visualização e dashboard!**
""")

print("\n🎉 Atividade concluída com sucesso!")

============================================================
📊 RESUMO DO PROCESSO DE LIMPEZA E PREPARAÇÃO
============================================================

Etapas realizadas e resultados:

| Etapa                          | Antes          | Depois         | Melhoria     |
|--------------------------------|----------------|----------------|--------------|
| Linhas totais                  |          228 |            3 |         -225 |
| Colunas totais                 |           11 |           10 |           -1 |
| Tipos corretos                 | Manual         | Automático     | ✅           |
| Valores nulos                  |           73 |            0 |          -73 |
| Duplicatas                     |            7 |            0 |           -7 |
| Variáveis derivadas            | 0              | 4              | +4           |
| Categorias padronizadas        | Inconsistentes | Padronizadas   | ✅           |

✅ **Base pronta para as próximas aulas de visualização e dashboard!**


🎉 Atividade concluída com sucesso!